version: '3'
services:
  db:
    build:
      context: ./docker
      dockerfile: mysql.dockerfile
    ports:
    - "3306:3306"
    container_name: meu_db
    volumes:
    - ./docker/volumes/mysql_volume:/var/lib/mysql