version: '3'
services:
  db:
    image: mysql:5.6
    ports:
      - "3308:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=senha
      - MYSQL_DATABASE=livro
      - MYSQL_USER=marcos
      - MYSQL_PASSWORD=senha
    container_name: meu_db